In [7]:
import torch

# Create a generator and set the seed
generator = torch.Generator().manual_seed(42)

# Use the generator in a random operation
random_tensor = torch.randn((2, 2), generator=generator)
random_tensor

tensor([[0.3367, 0.1288],
        [0.2345, 0.2303]])

In [8]:
# Use the generator in a random operation
random_tensor = torch.randn((2, 2), generator=generator)
random_tensor

tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]])

In [10]:
for i in range(5):
    rand = torch.rand((1, ), generator=generator)
    print(rand)

tensor([0.5782])
tensor([0.0600])
tensor([0.2846])
tensor([0.2007])
tensor([0.5014])


In [21]:
weights = torch.tensor([0, 7, 3, 0], dtype=torch.float) # create a tensor of weights
result = torch.multinomial(weights, 1000, replacement=True)
x1 = len([x for x in result if x == 1])
x2 = len([x for x in result if x == 2])
print(f"{x1/(x1+x2)}, {x2/(x1+x2)}")

0.697, 0.303
